'use client';
import {useEffect,useMemo,useState} from 'react';

export default function Page(){
 const [clients,setClients]=useState([]),[actions,setActions]=useState([]),[googleConfigured,setGoogleConfigured]=useState(false),[view,setView]=useState('Overview'),[active,setActive]=useState(null),[modal,setModal]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [searchData,setSearchData]=useState(null),[searchLoading,setSearchLoading]=useState(false),[sites,setSites]=useState([]),[siteLoading,setSiteLoading]=useState(false),[days,setDays]=useState(28);
 const [audits,setAudits]=useState([]),[auditLoading,setAuditLoading]=useState(false);
 const apply=d=>{setClients(d.clients||[]);setActions(d.actions||[]);setGoogleConfigured(!!d.googleConfigured)};
 const loadState=()=>fetch('/api/state',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Load failed');apply(d);return d});
 useEffect(()=>{loadState().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const p=new URLSearchParams(location.search),client=p.get('client');if(client){setActive(client);history.replaceState({},'',location.pathname)}},[]);
 const mutate=async body=>{setError('');const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed');apply(d)};
 const add=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate({kind:'client',name:f.get('name'),type:f.get('type'),site:f.get('site'),city:f.get('city')});setModal(false)}catch(e){setError(e.message)}};
 const toggle=async a=>{try{await mutate({kind:'action',id:a.id,completed:!a.completed})}catch(e){setError(e.message)}};
 const removeClient=async client=>{if(!confirm('Delete '+client.name+'? This permanently removes the client profile, Search Console connection, SEO snapshots, and technical audit history.'))return;try{await mutate({kind:'delete_client',id:client.id});if(active===client.id){setActive(null);setSearchData(null);setAudits([])}}catch(e){setError(e.message)}};
 const c=active&&clients.find(x=>x.id===active);
 const loadSites=async()=>{setSiteLoading(true);setError('');try{const r=await fetch('/api/google/sites?client='+encodeURIComponent(c.id),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load properties');setSites(d.sites||[])}catch(e){setError(e.message)}finally{setSiteLoading(false)}};
 const chooseSite=async siteUrl=>{try{const r=await fetch('/api/google/site',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client:c.id,siteUrl})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save property');await loadState();setSites([])}catch(e){setError(e.message)}};
 const loadSearch=async n=>{if(!c?.gsc_site_url)return;setSearchLoading(true);setError('');try{const r=await fetch('/api/search-console?client='+encodeURIComponent(c.id)+'&days='+n,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Search Console request failed');setSearchData(d)}catch(e){setError(e.message);setSearchData(null)}finally{setSearchLoading(false)}};
 useEffect(()=>{if(c?.gsc_site_url){setSearchData(null);loadSearch(days)}},[active,c?.gsc_site_url,days]);
 const loadAudits=async()=>{if(!c)return;try{const r=await fetch('/api/technical-audit?client='+encodeURIComponent(c.id),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load audit history');setAudits(d.audits||[])}catch(e){setError(e.message)}};
 const runAudit=async()=>{if(!c)return;setAuditLoading(true);setError('');try{const r=await fetch('/api/technical-audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client:c.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Technical audit failed');await loadAudits()}catch(e){setError(e.message)}finally{setAuditLoading(false)}};
 useEffect(()=>{if(c&&view==='Technical')loadAudits()},[active,view]);

 if(c){
  const s=searchData?.summary;
  return <Shell view={view} setView={setView}>
   <button className="back" onClick={()=>{setActive(null);setSearchData(null)}}>← All clients</button>
   <div className="clientHead"><div><p className="eyebrow">CLIENT WORKSPACE</p><h1>{c.name}</h1><p>{c.type} · {c.city} · {c.site}</p></div><div className="clientActions"><div className="range">{[7,28,90].map(n=><button key={n} className={days===n?'sel':''} onClick={()=>setDays(n)}>{n}D</button>)}</div><button className="danger" onClick={()=>removeClient(c)}>Delete client</button></div></div>
   <Tabs view={view} setView={setView}/>
   {error&&<div className="notice error"><b>Connection issue</b><span>{error}</span></div>}
   {!googleConfigured&&<div className="notice warn"><b>Google setup required</b><span>Add the Google OAuth environment variables in Vercel to enable Search Console authorization.</span></div>}
   {googleConfigured&&!c.gsc_connected&&<div className="connectBox"><div><h3>Connect Google Search Console</h3><p>Authorize read-only Search Console access for this client.</p></div><a className="buttonLink" href={'/api/google/connect?client='+encodeURIComponent(c.id)}>Connect Google</a></div>}
   {c.gsc_connected&&!c.gsc_site_url&&<div className="connectBox"><div><h3>Choose Search Console property</h3><p>The Google account is connected. Select which verified property belongs to {c.name}.</p></div><button onClick={loadSites}>{siteLoading?'Loading…':'Choose property'}</button></div>}
   {sites.length>0&&<article className="panel propertyList"><h3>Available Search Console properties</h3>{sites.map(x=><button key={x.siteUrl} onClick={()=>chooseSite(x.siteUrl)}><span>{x.siteUrl}</span><small>{x.permissionLevel}</small></button>)}</article>}
   <div className="stats"><Card t="Clicks" v={searchLoading?'…':fmt(s?.clicks)} s={c.gsc_site_url?days+'-day Search Console':'Search Console pending'} delta={searchData?.comparison?.clicks}/><Card t="Impressions" v={searchLoading?'…':fmt(s?.impressions)} s={c.gsc_site_url?days+'-day Search Console':'Search Console pending'} delta={searchData?.comparison?.impressions}/><Card t="CTR" v={searchLoading?'…':pct(s?.ctr)} s={c.gsc_site_url?days+'-day Search Console':'Search Console pending'} delta={searchData?.comparison?.ctr}/><Card t="Avg. position" v={searchLoading?'…':pos(s?.position)} s={c.gsc_site_url?days+'-day Search Console':'Search Console pending'} delta={searchData?.comparison?.position} positionDelta/></div>
   <h2>{view}</h2>
   <ClientPanel view={view} c={c} data={searchData} actions={actions} toggle={toggle} loading={searchLoading} audits={audits} runAudit={runAudit} auditLoading={auditLoading}/>
  </Shell>
 }
 return <Shell view={view} setView={setView}><header><div><p className="eyebrow">PORTFOLIO OVERVIEW</p><h1>SEO Command Center</h1><p>See visibility, spot opportunities, and track what OneTap improves.</p></div><button onClick={()=>setModal(true)}>+ Add Client</button></header>{error&&<div className="notice error"><b>Connection issue</b><span>{error}</span></div>}<div className="notice"><b>{loading?'Connecting…':'Database connected'}</b><span>{loading?'Loading persistent client data.':'Client and action changes survive refreshes and deployments.'}</span></div><div className="stats"><Card t="Clients" v={loading?'—':clients.length} s="Active portfolio"/><Card t="Open actions" v={loading?'—':actions.filter(a=>!a.completed).length} s="Persistent queue"/><Card t="Search data" v={clients.some(x=>x.gsc_site_url)?'Connected':'Pending'} s={clients.filter(x=>x.gsc_site_url).length+' properties mapped'}/><Card t="Health" v="Baseline" s="Audit engine next"/></div><h2>Client portfolio</h2><div className="clients">{clients.map(c=><article key={c.id}><div className="avatar">{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h3>{c.name}</h3><p>{c.type} · {c.site}</p></div><span className={'pill '+(c.gsc_site_url?'good':'')}>{c.gsc_site_url?'GSC Live':'Setup'}</span><div className="metric"><small>Clicks</small><b>—</b></div><div className="metric"><small>Impressions</small><b>—</b></div><div className="metric"><small>CTR</small><b>—</b></div><button className="open" onClick={()=>{setActive(c.id);setView('Overview')}}>Open →</button></article>)}</div><div className="grid"><div><h2>SEO Action Queue</h2>{actions.map(a=><Action key={a.id} a={a} toggle={toggle}/>)}</div><div><h2>Optimization loop</h2><article className="panel"><b>Measure → Diagnose → Improve → Verify</b><p>Persistent client data is live. Search Console now has a secure OAuth path and real analytics endpoints.</p></article></div></div>{modal&&<div className="modal"><form onSubmit={add}><h2>Add client</h2><input name="name" placeholder="Business name" required/><input name="type" placeholder="Business type"/><input name="site" placeholder="Website"/><input name="city" placeholder="City / service area"/><div><button type="button" className="cancel" onClick={()=>setModal(false)}>Cancel</button><button>Add client</button></div></form></div>}</Shell>}

function ClientPanel({view,c,data,actions,toggle,loading,audits,runAudit,auditLoading}){
 if(!c.gsc_site_url)return <article className="panel"><h3>Search Console setup not complete</h3><p>Connect Google and map a verified Search Console property above. Metrics will appear here once the property is selected.</p>{view==='Recommendations'&&actions.map(a=><Action key={a.id} a={a} toggle={toggle}/>)}</article>;
 if(loading)return <article className="panel"><h3>Loading verified Search Console data…</h3></article>;
 if(view==='Keywords')return <MetricTable title="Top queries" rows={data?.queries} type="query"/>;
 if(view==='Pages')return <MetricTable title="Top landing pages" rows={data?.pages} type="page"/>;
 if(view==='Search')return <article className="panel"><h3>Google Search performance</h3><p>{data?.startDate} → {data?.endDate} · {data?.siteUrl}</p><div className="checks">✓ Verified Search Console property<br/>✓ Read-only OAuth connection<br/>✓ Live clicks, impressions, CTR and average position<br/>✓ Query and landing-page data available</div></article>;
 if(view==='Technical'){const a=audits?.[0];return <article className="panel"><div className="panelHead"><div><h3>Technical SEO audit</h3><p>Live checks against the client's current website.</p></div><button onClick={runAudit} disabled={auditLoading}>{auditLoading?'Running audit…':a?'Run again':'Run audit'}</button></div>{a?<><div className="auditSummary"><Status label="Healthy" value={a.summary?.healthy||0} kind="healthy"/><Status label="Needs Attention" value={a.summary?.needs_attention||0} kind="needs_attention"/><Status label="Action Required" value={a.summary?.action_required||0} kind="action_required"/></div><p className="auditMeta">Last audit: {new Date(a.captured_at).toLocaleString()} · {a.url}</p><div className="auditChecks">{(a.checks||[]).map(x=><div className="auditCheck" key={x.id}><span className={'checkIcon '+x.status}></span><div><b>{x.label}</b><p>{x.evidence}</p></div><em>{x.status==='healthy'?'Healthy':x.status==='needs_attention'?'Needs Attention':'Action Required'}</em></div>)}</div>{audits.length>1&&<details className="auditHistory"><summary>Previous audits ({audits.length-1})</summary>{audits.slice(1).map(x=><p key={x.id}>{new Date(x.captured_at).toLocaleString()} — {x.summary?.healthy||0} healthy, {x.summary?.needs_attention||0} attention, {x.summary?.action_required||0} required</p>)}</details>}</>:<div className="emptyAudit"><b>No technical audit yet</b><p>Run the first audit to check HTTPS, titles, meta descriptions, H1 structure, canonicals, schema, image alt attributes, robots.txt, sitemap.xml, and optional PageSpeed performance.</p></div>}</article>}
 if(view==='Recommendations')return <article className="panel"><h3>SEO opportunities</h3><p>These suggestions are generated from the current Search Console data using transparent rules.</p><div className="recs">{data?.recommendations?.length?data.recommendations.map((r,i)=><div className="rec" key={r.title+i}><div><span className={'priority '+r.priority.toLowerCase()}>{r.priority}</span><small>{r.category}</small></div><h4>{r.title}</h4><p>{r.reason}</p><b>Suggested action</b><p>{r.action}</p></div>):<p>No rule-based opportunities were triggered for this period yet.</p>}</div></article>;
 if(view==='History')return <article className="panel"><h3>SEO snapshot history</h3><p>Each Search Console refresh stores the latest verified KPI snapshot.</p><div className="table historyTable"><div className="tr th"><span>Period</span><span>Clicks</span><span>Impr.</span><span>CTR</span><span>Position</span></div>{data?.history?.length?data.history.map((h,i)=><div className="tr" key={i}><span className="key">{h.range_days}D · {String(h.end_date).slice(0,10)}</span><span>{fmt(h.clicks)}</span><span>{fmt(h.impressions)}</span><span>{pct(h.ctr)}</span><span>{pos(h.position)}</span></div>):<p>No snapshots saved yet.</p>}</div></article>;
 if(view==='Overview')return <article className="panel"><h3>Search Console connected</h3><p>{data?.siteUrl}</p><p>The KPI cards compare the selected period against the immediately preceding period. Search Console snapshots are saved automatically so OneTap can build a performance history over time.</p>{data?.recommendations?.length>0&&<div className="opportunity"><b>{data.recommendations.length} SEO opportunit{data.recommendations.length===1?'y':'ies'} detected</b><button onClick={()=>document.querySelector('.tabs button:nth-child(8)')?.click()}>View recommendations</button></div>}</article>;
 return <article className="panel"><h3>{view}</h3><p>This module is ready for the next data source or workflow.</p></article>;
}
function MetricTable({title,rows=[],type}){return <article className="panel"><h3>{title}</h3><div className="table"><div className="tr th"><span>{type==='query'?'Query':'Page'}</span><span>Clicks</span><span>Impr.</span><span>CTR</span><span>Position</span></div>{rows.length?rows.map((r,i)=><div className="tr" key={(r.keys?.[0]||'row')+i}><span className="key">{r.keys?.[0]||'—'}</span><span>{fmt(r.clicks)}</span><span>{fmt(r.impressions)}</span><span>{pct(r.ctr)}</span><span>{pos(r.position)}</span></div>):<p>No data returned for this period.</p>}</div></article>}
function Shell({children,view,setView}){return <main><aside><b>OneTap Creative</b><span>SEO Command Center</span><nav>{['Overview','Clients','Search','Keywords','Pages','Local SEO','Technical','Leads','Action Queue','History'].map(x=><button key={x} className={view===x?'navsel':''} onClick={()=>setView(x)}>{x}</button>)}</nav><small>Internal workspace · V1.5</small></aside><section>{children}</section></main>}
function Tabs({view,setView}){return <div className="tabs">{['Overview','Search','Keywords','Pages','Local SEO','Technical','Leads','Recommendations','History'].map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'sel':''}>{x}</button>)}</div>}
function Card({t,v,s,delta,positionDelta}){let good=positionDelta?delta<0:delta>0;let label=delta==null?'':positionDelta?((delta>0?'+':'')+Number(delta).toFixed(1)+' pos'):(Math.abs(delta)<0.05?'0%':(delta>0?'+':'')+Number(delta).toFixed(1)+'%');return <article><span>{t}</span><b>{v??'—'}</b><small>{s}</small>{delta!=null&&<em className={'delta '+(good?'up':delta===0?'flat':'down')}>{label} vs previous period</em>}</article>}
function Action({a,toggle}){return <article className={'action '+(a.completed?'complete':'')}><span className={'dot '+a.priority.toLowerCase()}></span><div><b>{a.title}</b><small>{a.scope}</small></div><em>{a.completed?'Done':a.priority}</em><button onClick={()=>toggle(a)}>{a.completed?'Undo':'Complete'}</button></article>}
function Status({label,value,kind}){return <div className={'statusBox '+kind}><b>{value}</b><span>{label}</span></div>}
function fmt(v){return v==null?'—':Math.round(v).toLocaleString()}
function pct(v){return v==null?'—':(v*100).toFixed(1)+'%'}
function pos(v){return v==null?'—':Number(v).toFixed(1)}